project:
    name: gh-pm project
    number: 8
    owner: yahsan2
repositories:
    - yahsan2/gh-pm
defaults:
    priority: p1
    status: backlog
    labels:
        - pm-tracked
fields:
    priority:
        field: Priority
        values:
            p0: P0
            p1: P1
            p2: P2
    status:
        field: Status
        values:
            backlog: Backlog
            done: Done
            in_progress: In progress
            in_review: In review
            ready: Ready

triage:
    estimate:
        query: is:issue is:open status:backlog -has:estimate
        apply: {}
        interactive:
            estimate: true
    high-priority:
        query: is:issue is:open priority:p0
        apply: {}
        interactive: {}
    medium-priority:
        query: is:issue is:open priority:p1
        apply: {}
        interactive: {}
    backlog-p1:
        query: is:issue is:open status:backlog priority:p1
        apply: {}
        interactive: {}
    tracked:
        query: is:issue is:open -label:pm-tracked
        apply:
            labels:
                - pm-tracked
            fields:
                priority: p1
                status: backlog
        interactive:
            status: true
metadata:
    project:
        id: PVT_kwHOAAlRwM4BBvYB
    fields:
        status:
            id: PVTSSF_lAHOAAlRwM4BBvYBzg0KEU0
            options:
                done: "98236657"
                in_progress: 47fc9ee4
                in_review: df73e18b
                ready: 61e4505c
                todo: f75ad846
                backlog: f75ad846
        priority:
            id: PVTSSF_lAHOAAlRwM4BBvYBzg0KEX4
            options:
                p0: "79628723"
                p1: 0a877460
                p2: da944a9c
