project:
    name: gh-pm
    org: yahsan2
repositories:
    - yahsan2/gh-pm
defaults:
    priority: medium
    status: Todo
    labels:
        - pm-tracked
fields:
    priority:
        field: Priority
        values:
            critical: Critical
            high: High
            low: Low
            medium: Medium
    status:
        field: Status
        values:
            done: Done
            in_progress: In Progress
            in_review: In Review
            todo: Todo
