project:
    name: gh-pm project
    number: 8
    owner: yahsan2
repositories:
    - yahsan2/gh-pm
defaults:
    priority: p1
    status: backlog
    labels:
        - pm-tracked
fields:
    priority:
        field: Priority
        values:
            p0: P0
            p1: P1
            p2: P2
    status:
        field: Status
        values:
            backlog: Backlog
            done: Done
            in_progress: In progress
            in_review: In review
            ready: Ready
metadata:
    project:
        id: PVT_kwHOAAlRwM4BBvYB
    fields:
        status:
            id: PVTSSF_lAHOAAlRwM4BBvYBzg0KEU0
            options:
                done: "98236657"
                in_progress: 47fc9ee4
                in_review: df73e18b
                ready: 61e4505c
                todo: f75ad846
        priority:
            id: PVTSSF_lAHOAAlRwM4BBvYBzg0KEX4
            options:
                critical: "79628723"
                high: 0a877460
                medium: da944a9c
