# .golangci.yml
# golangci-lint configuration for gh-pm project

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - misspell
    - gofmt
    - goimports
  
  disable:
    - unused

linters-settings:
  goimports:
    local-prefixes: github.com/yahsan2/gh-pm

issues:
  exclude-dirs:
    - dist
    - vendor
    - .worktree
  
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    
    # Exclude fmt.Print* from errcheck
    - text: "Error return value of `fmt\\.(Print|Printf|Println|Fprint|Fprintf|Fprintln)` is not checked"
      linters:
        - errcheck