# .golangci.yml
# golangci-lint configuration for gh-pm project

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - misspell
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/yahsan2/gh-pm

issues:
  exclude-dirs:
    - dist
    - vendor
    - .worktree
  
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck