name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build and Release
        uses: cli/gh-extension-precompile@v2
        env:
          # gh-extension-precompile will automatically set version from tag
          GO_LDFLAGS: "-X github.com/yahsan2/gh-pm/cmd.Version=${{ github.ref_name }}"