name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Fix go.mod version for release
        run: |
          # Ensure go.mod uses 1.23 instead of 1.23.0 for release compatibility
          sed -i.bak 's/^go 1\.23\.0$/go 1.23/' go.mod
          rm go.mod.bak

      - name: Build and Release
        uses: cli/gh-extension-precompile@v2
        with:
          go_build_options: '-ldflags=-X=github.com/yahsan2/gh-pm/cmd.Version=${{ github.ref_name }}'
